version: 0.2

env: # テストケース実行時の環境変数
  variables:
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test

phases:
  install: # テストケースの実行に必要な環境を構築
    runtime-versions:
      python: 3.13
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands: # 前回のビルドで立ち上げた検証用コンテナを再利用しないために環境をクリーンアップ
      - docker compose down
      - docker container prune -f
  build:
    commands:
      - docker compose up -d # Docker Compose で検証用コンテナを立ち上げる
      - docker container ls -a
      - pytest # Docker Compose で立ち上げた検証用コンテナに `localhost` で接続するテストケースを実行: 接続エラーでビルドが失敗する
  post_build:
    commands: # ビルド終了時に環境をクリーンアップ
      - docker compose down
      - docker container prune -f
